substitutions:
  name: karlee_string_lights
  display_name: "Karlee String Lights"
  ipPrefix:  !secret ip_prefix
  id: "91"

<<: !include base.yaml

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    name: "${name}_button"
    internal: true
    on_press:
      - switch.toggle: relay
#      - light.toggle: blue_led
    
output:
  - platform: esp8266_pwm
    id: b_led
    pin:
      number: GPIO02
      inverted: True
  - platform: esp8266_pwm
    id: r_led
    pin:
      number: GPIO00
      inverted: True

light:
  - platform: monochromatic
    output: b_led
    id: blue_led
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    output: r_led
    id: red_led
    restore_mode: ALWAYS_OFF
    
switch:
- platform: gpio
  id: relay
  name: "${display_name}"
  pin: GPIO15
  restore_mode: ALWAYS_OFF
  on_turn_on:
    - light.turn_on: blue_led
  on_turn_off:
    - light.turn_off: blue_led
#- platform: gpio
#  name: "${name}_LED_Blue"
#  pin: GPIO02
#  inverted: True
#  restore_mode: ALWAYS_OFF
#- platform: gpio
#  name: "${name}_LED_Red"
#  pin: GPIO00
#  inverted: True
#  restore_mode: ALWAYS_OFF