substitutions:
  name: light-03
  display_name: Light 03
  ipPrefix:  !secret ip_prefix
  id: "98"
  
<<: !include base.yaml

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

#switch:
#  - platform: restart
#    name: ${display_name} Restart

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12

light:
  - platform: rgbww
    name: ${display_name}
    restore_mode: RESTORE_DEFAULT_ON
    constant_brightness: true
    color_interlock: true
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 1s
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
