
wifi:
  ssid: "SALNET"
  password: !secret network_psswd
  manual_ip:
    static_ip: "${ipPrefix}.${id}"
    gateway: !secret router_host
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${display_name} AP
    password: !secret fallback_psswd

captive_portal:

logger:

ota:
  password: !secret ota_psswd

#web_server: 

api: