substitutions:
  plug_name: seasonal_plug_2
  friendly_plug_name: "Seasonal Plug 2"

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'SALNET'
  password: !secret network_psswd
  manual_ip:
    static_ip: 192.168.1.97
    gateway: !secret router_host
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_plug_name} Hotspot"
    password: "P@ssword123"

captive_portal:

# Enable logging
logger:

# Enable Web server
#web_server:
#  port: 80

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    
#Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT
    name: "${plug_name}_button"
    internal: true
    on_press:
      - switch.toggle: ${plug_name}
      
  #- platform: status
  #  name: ${friendly_plug_name} Status
  #  id: ${plug_name}_status

#Led
output:
  - platform: gpio
    id: led1
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: binary
    internal: true
    output: led1
    id: status_led
    restore_mode: ALWAYS_OFF

#Relay    
switch:
- platform: gpio
  id: ${plug_name}
  name: "${friendly_plug_name}"
  pin: GPIO14
  restore_mode: ALWAYS_OFF
  on_turn_on:
    - light.turn_on: status_led
  on_turn_off:
    - light.turn_off: status_led