esphome:
  name: water_softener
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: "SALNET"
  password: !secret network_psswd
  manual_ip:
    static_ip: 192.168.1.82
    gateway: !secret router_host
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    unit_of_measurement: "%"
    icon: "mdi:cup-water"
    accuracy_decimals: 0
    name: "Water Softener Salt Level"
    update_interval: 60s
  
    filters:
      - lambda: return ((85-((x*100)-9))/85)*100;
      - filter_out: nan
